### PR TITLE
use `is-match` instead and a lil' bit stuff

### PR DESCRIPTION
**Pull request by tunnckoCore**
it's interesting how there wasn't `"dependencies": {}` section, lol...

### CODE REVIEW

**Comment by tunnckoCore** [comment]
hah, `confirmed-bug` in iojs@v2.2.0 fails https://github.com/nodejs/io.js/issues/1850

**Comment by jonschlinkert** [comment]
I'll merge since I need most of the changes, but `make-iterator` is still necessary for non-string/non-array arguments. thanks!

**Comment by jonschlinkert** [comment]
nvm, I don't have time to mess with it lol

**Comment by tunnckoCore** [comment]
Thanks!

> but make-iterator is still necessary for non-string/non-array arguments

mm, i dont think so. `filter` is passed to isMatch so it accepts all kinds - strings, regexp, array, function and etc.

**Pull request merged**
