### PR TITLE
update README to es6 (const and arrow function)

### PR DESCRIPTION
**Pull request by oprogramador**

### CODE REVIEW

**Comment by oprogramador** [comment]
@jonschlinkert @tunnckoCore @doowb @someone235 

what do you think about this PR?

I know this breaks compatibility with old Node.js versions but es6 was introduced above 2 years ago so I think we don't have to support such old versions

**Comment by tunnckoCore** [comment]
im okey with that, but it depends

**Comment by someone235** [comment]
Looks good. It's pretty standard to write your README in ES6. And about Node v4, it is outdated long time ago, so there's no reason to support it (Although it might be better to make a seprate PR for it).

**Comment by oprogramador** [comment]
@jonschlinkert 

could you review/ merge?

**Comment by oprogramador** [comment]
@jonschlinkert

**Pull request closed without merging**
