### PR TITLE
add support for glob filters using `micromatch`

### PR DESCRIPTION
**Pull request by tunnckoCore**
- support filters as strings or arrays of glob patterns
- tests for the support

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks for doing this, but how would this differ from https://github.com/jonschlinkert/filter-object then?

**Comment by tunnckoCore** [comment]
Because it use glob patterns to filter only object's keys?

Actually, I think `filter-object` should be able to filter objects by keys and by values. `filter-keys` filter only keys with `cb` or `glob`, same for the `filter-values`

**Comment by jonschlinkert** [comment]
Hmm, good point(s). I agree, I'll get this merged. thanks for explaining

**Comment by tunnckoCore** [comment]
Because the current use case
I have object that keys are color names, values are hex.

``` js
webColors()
//=> {pink: '#ffc0cb',
//  red: '#ff0000',
//  seashell: '#fff5ee',
//  snow: '#fffafa',
//  tomato: '#ff6347',
//  white: '#ffffff',
//  yellow: '#ffff00'}
webColors('red')
//=> '#ff0000'
webColors('#ff0000')
//=> 'red'
webColors('#ff*')
//=> ['#ffe4c4','#ffebcd','#ff7f50', ..., '#fff8dc']
webColors('g*')
//=> ['green', 'gray', 'grey', 'gainsboro', ..., 'goldenrod']
```

So
- if object hasOwnProperty given string, return value
- if isHex and isGlob - filter object values, return array
- if isGlob - filter object keys, return array

Thanks! :)

**Comment by jonschlinkert** [comment]
did you create that? Honest to god I just created a web-colors pkg but haven't pushed it up yet. here is the help: 

``` js
console.log(colors);
// Results in:
// { aqua:    '00ffff',
//   black:   '000000',
//   blue:    '0000ff',
//   fuchsia: 'ff00ff',
//   gray:    '808080',
//   green:   '008000',
//   lime:    '00ff00',
//   maroon:  '800000',
//   navy:    '000080',
//   olive:   '808000',
//   purple:  '800080',
//   red:     'ff0000',
//   silver:  'c0c0c0',
//   teal:    '008080',
//   white:   'ffffff',
//   yellow:  'ffff00'}
```

I didn't add filtering to it though, you could publish `filter-colors` or something like that :)

**Comment by tunnckoCore** [comment]
Hahaahah.. we are awesome twins!

**Comment by tunnckoCore** [comment]
Yea i was thinking for `filter-colors` This is it for now.. only need merge ;d

``` js
var colors = require('css-color-names');
var isGlob = require('is-glob');
var isHex = require('is-hex-color');
var filterValues = require('filter-values');
var filterKeys = require('filter-keys');

var webColors = module.exports = function webColors(str) {
  if (!str) {
    return colors;
  }

  if (typeof str !== 'string') {
    throw new TypeError('webc-colors: expect `str` to be string');
  }

  if (colors.hasOwnProperty(str)) {
    return colors[str];
  }

  if (isHex(str) || str.charAt(0) === '#' && isGlob(str)) {
    return filterValues(colors, str);
  }

  if (isGlob(str)) {
    return filterKeys(colors, str);
  }
};
webColors.names = function webColorNames() {
  return Object.keys(colors);
};
webColors.hex = function webColorHex() {
  return webColors('#*');
};
```

**Comment by tunnckoCore** [comment]
The initial idea was to just export web color names, then create web-colors-regex, that check if string is hex or some of possible color names, but grow to this

**Comment by jonschlinkert** [comment]
nice. I'll get this merged in a bit. thanks!

**Comment by tunnckoCore** [comment]
Okey. Can I publish this as `web-colors`? Thoughts?

**Comment by jonschlinkert** [comment]
seems like `filter-web-colors` makes more sense. make it semantic.

**Comment by jonschlinkert** [comment]
it's up to you obviously

**Pull request merged**
